#!/bin/bash

SSH_PORT=55555
HTTP_PORT=80
HTTPS_PORT=443
SMTP_PORT=25

#Flush iptables
sudo iptables -F
sudo iptables -X
sudo iptables -t nat -F
sudo iptables -t nat -X
sudo iptables -t mangle -F
sudo iptables -t mangle -X
sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT

#Blocking all
sudo iptables -P INPUT DROP
sudo iptables -P FORWARD DROP
sudo iptables -P OUTPUT DROP


#PORT SCAN
sudo iptables -A INPUT -p TCP -m state --state NEW -m recent --set
sudo iptables -A INPUT -p TCP -m state --state NEW -m recent --update --seconds 1 --hitcount 10 -j DROP

#DOS - This rule limits the ammount of connections from the same IP in a short time
sudo iptables -I INPUT -p TCP --dport ${SSH_PORT} -i enp0s3 -m state --state NEW -m recent --set
sudo iptables -I INPUT -p TCP --dport ${SSH_PORT} -i enp0s3 -m state --state NEW -m recent --update --seconds 60 --hitcount 10 -j DROP
sudo iptables -I INPUT -p TCP --dport ${HTTP_PORT} -i enp0s3 -m state --state NEW -m recent --set
sudo iptables -I INPUT -p TCP --dport ${HTTP_PORT} -i enp0s3 -m state --state NEW -m recent --update --seconds 60 --hitcount 10 -j DROP
sudo iptables -I INPUT -p TCP --dport ${HTTPS_PORT} -i enp0s3 -m state --state NEW -m recent --set
sudo iptables -I INPUT -p TCP --dport ${HTTPS_PORT} -i enp0s3 -m state --state NEW -m recent --update --seconds 60 --hitcount 10 -j DROP
sudo iptables -I INPUT -p TCP --dport ${SMTP_PORT} -i enp0s3 -m state --state NEW -m recent --set
sudo iptables -I INPUT -p TCP --dport ${SMTP_PORT} -i enp0s3 -m state --state NEW -m recent --update --seconds 60 --hitcount 10 -j DROP

#Keeping connections already ESTABLISHED
sudo iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

#Accept lo
sudo iptables -t filter -A INPUT -i lo -j ACCEPT
sudo iptables -t filter -A OUTPUT -o lo -j ACCEPT

#ACCEPT SSH
sudo iptables -A INPUT -p TCP --dport ${SSH_PORT} -j ACCEPT
sudo iptables -A OUTPUT -p TCP --dport ${SSH_PORT} -j ACCEPT

#ACCEPT HTTP
sudo iptables -A INPUT -p TCP --dport ${HTTP_PORT} -j ACCEPT
sudo iptables -A OUTPUT -p TCP --dport ${HTTP_PORT} -j ACCEPT

#ACCEPT HTTPS
sudo iptables -A INPUT -p TCP --dport ${HTTPS_PORT} -j ACCEPT
sudo iptables -A OUTPUT -p TCP --dport ${HTTPS_PORT} -j ACCEPT

#ACCEPT SMTP
sudo iptables -t filter -A INPUT -p tcp --dport 25 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 25 -j ACCEPT

#ACCEPT PING
sudo iptables -t filter -A INPUT -p icmp -j ACCEPT
sudo iptables -t filter -A OUTPUT -p icmp -j ACCEPT

exit 0